# Generated by Django 5.1.4 on 2024-12-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_blog',
            name='image',
            field=models.ImageField(upload_to='blog_images/'),
        ),
    ]
