# Generated by Django 5.1.4 on 2024-12-16 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_tbl_logintable'),
        ('User', '0002_alter_tbl_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog',
            name='user',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='Authentication.tbl_logintable'),
            preserve_default=False,
        ),
    ]
