# Generated by Django 5.1.4 on 2024-12-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_tbl_userprofile_password'),
        ('User', '0003_tbl_blog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='User.tbl_blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.tbl_logintable')),
            ],
        ),
    ]
