# Generated by Django 5.1.4 on 2024-12-17 07:40

from django.db import migrations, models
from django.utils import timezone



class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
