# Generated by Django 5.1.4 on 2024-12-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_tbl_userprofile_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_userprofile',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
