# Generated by Django 5.1.4 on 2024-12-17 08:48

import django.db.models.deletion
from django.db import migrations, models

def set_initial_login_values(apps, schema_editor):
    UserProfile = apps.get_model('Authentication', 'tbl_userprofile')
    LoginTable = apps.get_model('Authentication', 'tbl_logintable')
    
    # Create a login entry for each user and assign it
    for userprofile in UserProfile.objects.all():
        login = LoginTable.objects.create(
            username=userprofile.username,  # Or any other logic
            password='default_password',    # Replace with actual passwords if hashed
            type='user_type',               # Set an appropriate type
        )
        userprofile.login = login
        userprofile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_tbl_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_userprofile',
            name='login',
            field=models.OneToOneField(on_delete=models.CASCADE, null=True, related_name='profile', to='Authentication.tbl_logintable'),
        ),
        migrations.RunPython(set_initial_login_values),
        migrations.AlterField(
            model_name='tbl_userprofile',
            name='login',
            field=models.OneToOneField(on_delete=models.CASCADE, related_name='profile', to='Authentication.tbl_logintable'),
        ),
    ]
