# Generated by Django 5.1.4 on 2024-12-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_tbl_userprofile_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_logintable',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tbl_userprofile',
            name='login',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Authentication.tbl_logintable'),
        ),
    ]
